name: Validate with HACS

on:
  workflow_dispatch:

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: hacs/action@main
        with:
            category: "integration"